services:
  - type: web
    name: tt-printhub-orienteer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u app.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
